#!/usr/bin/env bash
# Waits for the root Application and at least one ApplicationSet-generated
# postgres Application to be Synced and Healthy. This is bootstrap's proof
# that repository authentication and generation both work end to end.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "$SCRIPT_DIR/../scripts/lib/env.sh"

TIMEOUT_SECONDS=300
INTERVAL_SECONDS=5

wait_synced_healthy() {
  local app="$1"
  local elapsed=0
  while (( elapsed < TIMEOUT_SECONDS )); do
    local sync health
    sync="$(kubectl get application.argoproj.io "$app" -n argocd -o jsonpath='{.status.sync.status}' 2>/dev/null || true)"
    health="$(kubectl get application.argoproj.io "$app" -n argocd -o jsonpath='{.status.health.status}' 2>/dev/null || true)"
    if [[ "$sync" == "Synced" && "$health" == "Healthy" ]]; then
      echo "$app: Synced/Healthy"
      return 0
    fi
    sleep "$INTERVAL_SECONDS"
    elapsed=$((elapsed + INTERVAL_SECONDS))
  done
  echo "Timed out waiting for $app to be Synced/Healthy (last sync=$sync health=$health)" >&2
  return 1
}

kubectl annotate application root -n argocd argocd.argoproj.io/refresh=hard --overwrite >/dev/null
wait_synced_healthy root

find_postgres_app() {
  kubectl get applications.argoproj.io -n argocd -o name 2>/dev/null \
    | sed 's#.*/##' | grep '^postgres-' | head -1 || true
}

pg_app="$(find_postgres_app)"
elapsed=0
while [[ -z "$pg_app" && $elapsed -lt $TIMEOUT_SECONDS ]]; do
  sleep "$INTERVAL_SECONDS"
  elapsed=$((elapsed + INTERVAL_SECONDS))
  pg_app="$(find_postgres_app)"
done

if [[ -z "$pg_app" ]]; then
  echo "No postgres-<tenant> Application was generated by the ApplicationSet within ${TIMEOUT_SECONDS}s." >&2
  exit 1
fi

wait_synced_healthy "$pg_app"
echo "root and $pg_app are both Synced/Healthy."
