{{- if not .Values.migrationsOnly }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fake-service.name" . }}
  labels:
    {{- include "fake-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  progressDeadlineSeconds: {{ .Values.progressDeadlineSeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "fake-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fake-service.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "fake-service.name" . }}
      containers:
        - name: {{ include "fake-service.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["/bin/sh", "-c", "echo starting version=${VERSION} release=${RELEASE_ID}; sleep infinity"]
          env:
            - name: VERSION
              value: {{ .Values.version | quote }}
            - name: RELEASE_ID
              value: {{ .Values.releaseId | quote }}
          readinessProbe:
            exec:
              command: ["true"]
            initialDelaySeconds: 1
            periodSeconds: 2
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- end }}
