{{- if not .Values.migrationsOnly }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fake-service.name" . }}
  labels:
    {{- include "fake-service.labels" . | nindent 4 }}
{{- end }}
