apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb
data:
  01-extra-databases.sql: |
    {{- range .Values.extraDatabases }}
    SELECT 'CREATE DATABASE {{ . }}' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '{{ . }}')\gexec
    {{- end }}
