apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
type: Opaque
stringData:
  username: {{ .Values.username | quote }}
  password: {{ .Values.password | quote }}
